### ISSUE TITLE
Create a job market candidates page

### ISSUE THREAD

**Issue by jdebacker** [UofSCEcon/UofSCEcon.github.io#8]
For the upcoming econ job market, we should create a job market candidates page.  Students on the market should be listed with:

* research areas
* job market paper title (and link to paper)
* link to CV
* link to personal webpage
* advisors (with links to their pages or email)

This page should also list the placement coordinator (in our case, this is our PhD program director, Dr. Ozturk).

cc @ernbilen

**Comment by ernbilen** [comment]
Sounds good! Shall I make a pull request for the page together with pdfs for the files and an image?

**Comment by jdebacker** [comment]
@ernbilen - Yes - if you could add this page with a PR, that'd be great - we can link with a box (like the PhD students box) in `index.html`.

No need to upload and pdfs - all docs (job market papers, CVs, etc) should be links from candidates personal pages so that they can update easily themselves.

**Comment by jdebacker** [comment]
This issue was resolved by @ernbilen with PR #11
